In [1]:
import pandas as pd

results = pd.read_csv("../report/cp1_experiments.csv")
results

,model,split,roc_auc,pr_auc,f1,precision,recall,accuracy
0,random_forest,validation,0.591536,0.558134,0.545410,0.539068,0.551903,0.563367
1,logistic_regression,validation,0.587508,0.555707,0.549950,0.535964,0.564686,0.561367
2,decision_tree,validation,0.574738,0.537499,0.568308,0.519867,0.626703,0.548133
3,dummy_most_frequent,validation,0.500000,0.474600,0.000000,0.000000,0.000000,0.525400
4,random_forest,test,0.588801,0.559746,0.541890,0.534540,0.549445,0.559100

На CP1 были обучены первые baseline-модели:

DummyClassifier;
LogisticRegression;
DecisionTreeClassifier;
RandomForestClassifier.

Чтобы получить начальное качество и сравнить простые модели.

In [2]:
validation_results = results[results["split"] == "validation"]
validation_results.sort_values("roc_auc", ascending=False)

,model,split,roc_auc,pr_auc,f1,precision,recall,accuracy
0,random_forest,validation,0.591536,0.558134,0.545410,0.539068,0.551903,0.563367
1,logistic_regression,validation,0.587508,0.555707,0.549950,0.535964,0.564686,0.561367
2,decision_tree,validation,0.574738,0.537499,0.568308,0.519867,0.626703,0.548133
3,dummy_most_frequent,validation,0.500000,0.474600,0.000000,0.000000,0.000000,0.525400

Лучшая модель на CP1 выбирается по ROC-AUC на validation split.

In [3]:
test_results = results[results["split"] == "test"]
test_results

,model,split,roc_auc,pr_auc,f1,precision,recall,accuracy
4,random_forest,test,0.588801,0.559746,0.54189,0.53454,0.549445,0.5591

Internal test split используется только после выбора лучшей модели на validation.
Файл `test.csv` из Kaggle не используется для оценки качества, потому что в нём нет таргета.